name: Discord Reminder

on:
  schedule:
    - cron: '30 4 */2 * *'  # 10:00 AM IST
  workflow_dispatch:        # allows manual run

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Run script
        run: node index.js
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
